config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root 'homes#top'

    get 'homes/about' => 'homes#about', as: 'about'
    #get 'customers/mypage' => 'customers#show', as: 'mypage'
    #get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    #patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/withdraw' => 'customers#withdraw', as: 'confirm_withdraw'
    patch 'customers/out' => 'customers#out', as: 'out_customer'
    get '/search', to: 'searches#search'
    get 'shearch/result' => 'searches#result'
    

    resources :customers, only:[:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :impressions do
      resources :comments, only:[:create,:edit,:update,:destroy]
      collection do
        get "confirm"
      end
    end


  end

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'

    resources :impressions, only:[:index,:show,:destroy] do
      resources :comments, only:[:create,:edit,:update,:destroy]
    end
    
    resources :customers, only:[:index,:show,:edit,:update,:destroy]
    resources :genres, only:[:new,:create,:index,:edit,:update,:destroy]

  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :impressions
  
  validates :name, presence: true
  
  def self.search_for(content, method)
    if method == "perfect"
      Genre.where(name: content)
    elsif method == "forward"
      Genre.where("name LIKE?",content+'%')
    elsif method == "backward"
      Genre.where("name LIKE?",'%'+content)
    elsif method == "partial"
      Genre.where("name LIKE?",'%'+content+'%')
    end
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :new
    end
  end

  def index
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path

  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end


  private
  
  def authenticate
    redirect_to new_admin_session_path unless admin_signed_in?
  end

  def genre_params
    params.require(:genre).permit(:name,:is_active)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h3>ジャンル編集</h3>

<%= form_with model: @genre, url: admin_genre_path do |f| %>
  <%= f.label :"ジャンル名" %>
  <%= f.text_field :name %>
  <%= f.radio_button :is_active, true %>
  <%= f.label :is_active,"有効", class: "text-active" %>
  <%= f.radio_button :is_activem, false %>
  <%= f.label :is_active,"無効", class:"text-invalid" %>
  
  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/genres/index.html.erb
<div class="container">
  
  <h3>ジャンル一覧</h3>
  
  <div class="btn btn-primary">
    <%= link_to 'ジャンル追加', new_admin_genre_path, class:'text-white' %>
  </div>
  <table>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to "編集", edit_admin_genre_path(genre.id), class:"btn btn-outline-success" %></td>
        <td><%= link_to "削除", admin_genre_path(genre.id),method: :delete, class:"btn btn-outline-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/genres/new.html.erb
<div class="container">
  
  <div class="row">
    <div class="mx-auto">
      <h3>ジャンル追加</h3>
    </div>
  </div>
  
  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <%= f.text_field :name %>
        <%= f.submit '追加', class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
  
</div>