config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root 'homes#top'

    get 'homes/about' => 'homes#about', as: 'about'
    #get 'customers/mypage' => 'customers#show', as: 'mypage'
    #get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    #patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/withdraw' => 'customers#withdraw', as: 'confirm_withdraw'
    patch 'customers/out' => 'customers#out', as: 'out_customer'
    get '/search', to: 'searches#search'
    get 'shearch/result' => 'searches#result'
    

    resources :customers, only:[:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :impressions do
      resources :comments, only:[:create,:edit,:update,:destroy]
      collection do
        get "confirm"
      end
    end


  end

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'

    resources :impressions, only:[:index,:show,:destroy] do
      resources :comments, only:[:create,:edit,:update,:destroy]
    end
    
    resources :customers, only:[:index,:show,:edit,:update,:destroy]
    resources :genres, only:[:new,:create,:index,:edit,:update,:destroy]

  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @customers = Customer.all
    @impressions = Impression.all
  end
  
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h3>admin top</h3>
    </div>
  </div>
  
  <div class="row">
    <div class="col-10 mx-auto">
      <p>会員管理</p>
      <div class="table">
        <table>
          <thead>
            <tr>
              <th class="col-2">ユーザーネーム</th>
              <th class="col-2">投稿数</th>
              <th class="col-2"><%= link_to '一覧へ', admin_customers_path, class: "btn btn-info" %></th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.user_name %></td>
              <td><%= customer.impressions.count %></td>
              <td><%= link_to "show more", admin_customer_path(customer), class: "btn btn-primary" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      
      
      <p>投稿管理</p>
      <div class="table">
        <table>
          <thead>
            <tr>
              <th class="col-2">投稿日</th>
              <th class="col-2">投稿者</th>
              <th class="col-4">本文</th>
              <th class="col-2"><%= link_to '一覧へ', admin_impressions_path, class: "btn btn-info" %></th>
            </tr>
          </thead>
          <tbody>
            <% @impressions.each do |impression| %>
            <tr>
              <td><%= impression.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= impression.customer.user_name %></td>
              <td><%= impression.body %></td>
              <td><%= link_to 'show more', admin_impression_path(impression), class: "btn btn-primary" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  
</div>