config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root 'homes#top'

    get 'homes/about' => 'homes#about', as: 'about'
    #get 'customers/mypage' => 'customers#show', as: 'mypage'
    #get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    #patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/withdraw' => 'customers#withdraw', as: 'confirm_withdraw'
    patch 'customers/out' => 'customers#out', as: 'out_customer'
    get '/search', to: 'searches#search'
    get 'shearch/result' => 'searches#result'
    

    resources :customers, only:[:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :impressions do
      resources :comments, only:[:create,:edit,:update,:destroy]
      collection do
        get "confirm"
      end
    end


  end

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'

    resources :impressions, only:[:index,:show,:destroy] do
      resources :comments, only:[:create,:edit,:update,:destroy]
    end
    
    resources :customers, only:[:index,:show,:edit,:update,:destroy]
    resources :genres, only:[:new,:create,:index,:edit,:update,:destroy]

  end


end

app/models/impression.rb
class Impression < ApplicationRecord
  belongs_to :customer
  belongs_to :genre,optional: true
  has_many :comments, dependent: :destroy
  
  
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true


  def self.search_for(content, method)
    if method == "perfect"
      Impression.where(title: content)
    elsif method == "forward"
      Impression.where("title LIKE?",content+'%')
    elsif method == "backward"
      Impression.where("title LIKE?",'%'+content)
    elsif method == "partial"
      Impression.where("title LIKE?",'%'+content+'%')
    end
  end
  
  enum status: { published: 0, draft: 1 }
  
end

app/controllers/admin/impressions_controller.rb
class Admin::ImpressionsController < ApplicationController
  before_action :authenticate
  
  def index
    @impressions = Impression.all.page(params[:page]).per(10)
  end
  
  def show
    @impression = Impression.find(params[:id])
  end
  
  def destroy
    @impression = Impression.find(params[:id])
    @impression.destroy
    redirect_to admin_impressions_path
  end
  
  private

  def authenticate
    redirect_to new_admin_session_path unless admin_signed_in?
  end
  
end

app/helpers/admin/impressions_helper.rb
module Admin::ImpressionsHelper
end

app/views/admin/impressions/_show_rate.html.erb
<div id="show-rate-<%= impression.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#show-rate-<%= impression.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= impression.rate %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/admin/impressions/_star_rate.html.erb
<% if impression.id.nil? %>
  <div class="form-group" id="star">
    <%= f.label :"評価" %>
    <%= f.hidden_field :rate, id: :review_star, class: 'form-control' %>
    <div id="post_raty"></div>
  </div>
  
  <script>
    $(document).on('turbolinks:load', function() {
      let elem = document.querySelector('#post_raty');
      if (elem == null) return;

      elem.innerHTML = ""
      let opt = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'impression[rate]',
      };
      raty(elem, opt);
     });
  </script>
<% else %>
  <div class="form-group">
    <%= render "show_rate", impression: impression %>
  </div>
<% end %>

app/views/admin/impressions/edit.html.erb
<div class="container">
  <div class="row mb-3">
    <h3>感想編集</h3>
  </div>

  <div class="row mb-3">
    <%= form_with model: @impression, local: true do |f| %>
      <div class="form-group">
        <%= f.label :"ゲームタイトル" %>
        <%= f.text_field :title, class: 'form-control impression_title' %>
      </div>
      <div class="form-group">
        <%= f.label :"感想" %>
        <%= f.text_area :body, class: 'form-control impression_body' %>
      </div>
      <div class="form-group">
        <%= f.label :"ジャンル" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :name, {promt: "選択してください"}, class: 'form-control impression_genre' %>
      </div>
      
      <div class="form-group" id="star">
        <%= f.label :rate %>
        <%= f.hidden_field :rate, id: :review_star, class: 'form-control' %>
        <div id="post_raty"></div>
      </div>
      
      <script>
        $(document).on('turbolinks:load', function() {
          let elem = document.querySelector('#post_raty');
          if (elem == null) return;
    
          elem.innerHTML = ""
          let opt = {  
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: <%= @impression.rate %>,
            scoreName: 'impression[rate]',
          };
          raty(elem, opt);
        });
      </script>
      
      <div class="form-group">
        <%= f.submit '保存する', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/impressions/index.html.erb
<div class="container">
  
  <div class="row mx-auto">
    <div class="col-4">
      <h3>感想一覧</h3>
    </div>
  </div>
  
  <div class="row">
    <div class="table col-10">
      <table>
        <thead>
          <tr>
            <th>投稿者</th>
            <th>ゲームタイトル</th>
            <th>感想本文</th>
            <th>評価</th>
            <th></th>
            <th>コメント数</th>
          </tr>
        </thead>
      <% @impressions.each do |impression| %>
        <tbody>
          <tr>
            <td><%= link_to impression.customer.user_name,admin_customer_path(impression.customer_id) %></td>
            <td class="col-2"><%= impression.title %></td>
            <td class="col-4"><%= impression.body %></td>
            <td><%= render 'star_rate', impression: impression %></td>
            <td><%= link_to "show more", impression_path(impression.id) %></td>
            <td><%= link_to "#{impression.comments.count}コメント", admin_impression_path(impression.id) %></td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
  <%= paginate @impressions %>
</div>

app/views/admin/impressions/show.html.erb
<div class="container">
  <div class="row">
    <div class="table mx-auto">
      <h4>感想詳細</h4>
      <table>
        <tbody>
          <tr>
            <td class="col-2">タイトル</td>
            <td class="col-6"><%= @impression.title %></td>
          </tr>
          <tr>
            <td>本文</td>
            <td><%= @impression.body %></td>
          </tr>
          <tr>
            <td>評価</td>
            <td><%= render 'show_rate', impression: @impression %></td>
          </tr>
          <tr>
            <td>投稿者</td>
            <td><%= @impression.customer.user_name %></td>
          </tr>
        </tbody>
      </table>
      <%= link_to '削除する', impression_path(@impression), class:"btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
    </div>
  </div>
  <div class="row">
    <div class="table mx-auto">
      <h4>コメント</h4>
      <table>
        <thead>
          <tr>
            <th class="col-2">投稿者</th>
            <th class="col-4">コメント</th>
            <th class="col-2">投稿日</th>
          </tr>
        </thead>
        <tbody>
          <% @impression.comments.each do |comment| %>
          <tr>
            <td><%= comment.customer.user_name %></td>
            <td><%= comment.post_comment %></td>
            <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>