config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root 'homes#top'

    get 'homes/about' => 'homes#about', as: 'about'
    #get 'customers/mypage' => 'customers#show', as: 'mypage'
    #get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    #patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/withdraw' => 'customers#withdraw', as: 'confirm_withdraw'
    patch 'customers/out' => 'customers#out', as: 'out_customer'
    get '/search', to: 'searches#search'
    get 'shearch/result' => 'searches#result'
    

    resources :customers, only:[:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :impressions do
      resources :comments, only:[:create,:edit,:update,:destroy]
      collection do
        get "confirm"
      end
    end


  end

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'

    resources :impressions, only:[:index,:show,:destroy] do
      resources :comments, only:[:create,:edit,:update,:destroy]
    end
    
    resources :customers, only:[:index,:show,:edit,:update,:destroy]
    resources :genres, only:[:new,:create,:index,:edit,:update,:destroy]

  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamerlife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag'logo.png', size:"120x60" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
              <% if admin_signed_in? %>
              <li class="nav-item mr-1">
                <%= link_to '会員管理', admin_customers_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to '感想管理', admin_impressions_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to 'ジャンル管理', admin_genres_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              
              <% elsif customer_signed_in? %>
              <p>ようこそ、<%= current_customer.user_name %>さん！</p>
              <li class="nav-item mr-1">
                <%= link_to 'マイページ', customer_path(current_customer.id), class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to '会員一覧', customers_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to '感想一覧', impressions_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to '下書き一覧', confirm_impressions_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              
              <% else %>
              <li class="nav-item mr-1">
                <%= link_to '感想一覧', impressions_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link btn btn-outline-secondary' %>
              </li>
              <% end %>
            </ul>
          </div>
          
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <div class="d-flex justify-content-center mb-2">
        <%= render 'public/searches/search' %>
      </div>
    <%= yield %>
    </main>

    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>思うままにGamerLife</p>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <%= link_to "概要", about_path, class:"text-white-50" %>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>